ReadSpeaker||(ReadSpeaker={});ReadSpeaker.DocReader||(ReadSpeaker.DocReader={});
ReadSpeaker.DocReader.AutoAdd=function(){var l=function(d){var b=d.href,a=d.className;d=d.innerHTML.toLowerCase();if(b&&1<b.length){if(a.match(new RegExp(c.drAddedClass,"i"))||a.match(/rspkr_dr_link/i))return!1;var f=new RegExp("("+c.doc_list.join("|")+")([^a-zA-Z0-9]|$)","i");if(b.match(f)||a.match(new RegExp(c.drClass,"i")))return!0;a=new RegExp("("+c.textExclude.join("|")+")","i");return d.match(a)?!1:!!b.match("/bbcswebdav/")}return!1},c={cid:"[[DOCREADERID]]",doc_list:"\\.doc \\.docx \\.odt \\.pdf \\.rtf \\.ppt \\.pptx \\.xls \\.xlsx \\.epub type=drlink".split(" "),
img_href:document.location.protocol+"//media.readspeaker.com/images/buttons/listen_icons/icon_16px.gif",img_alt:"Open this document with ReadSpeaker docReader",lang:"en_us",useHrefLang:!0,docReaderOnly:!1,drClass:"rspkr_add_drlink",drAddedClass:"rspkr_dr_added",textExclude:["mp3","zip","mp4"],revision:"@@%RELEASE%"};return{init:function(){if("object"===typeof window.rsDocReaderConf){var d=window.rsDocReaderConf,b;b=c;for(var a in d)d.hasOwnProperty(a)&&(b[a]=d[a])}b=document.getElementsByTagName("A");
d=[];for(a=0;a<b.length;a++)d[a]=b[a];for(b=0;b<d.length;b++)if(l(d[b])){var f;a=d[b].href;f="";f=-1<a.indexOf("http")||-1<a.indexOf("https")?a:0==a.indexOf("/")?document.location.protocol+"://"+document.location.hostname+a:-1==a.indexOf("/")?document.location.protocol+"://"+document.location.hostname+document.location.pathname+a:a;if(""!==f){a=d[b];var k=f,g=document.createElement("img");g.setAttribute("src",c.img_href);g.setAttribute("alt",c.img_alt);g.setAttribute("title",c.img_alt);g.style.border=
"0px";g.style.display="inline";g.style.margin="0px";g.style.position="absolute";var h=a.getAttribute("hreflang");h&&""!==h&&!1!==c.useHrefLang||(h=c.lang);f=document.createElement("a");var e="/webapps/rs-readspeaker-bb_bb60/",m=!1;"function"===typeof $rs.arr&&(m=$rs.arr("#rs_Req_blackboard"),0<m.length&&(e=$rs.getAttr(m[0],"data-rsvalue-uristem")));e+="open2.jsp";e+="?cid=REPLACE_CID&lang=REPLACE_LANG&url=REPLACE_URL&rsurl=REPLACE_RSURL";e=e.replace("REPLACE_CID",c.cid);e=e.replace("REPLACE_LANG",
h);e=e.replace("REPLACE_URL",encodeURIComponent(k));e=e.replace("REPLACE_RSURL",encodeURIComponent(document.location.protocol+"//docreader.readspeaker.com/docreader/"));k=document.location.href.split("?");if(k[1])for(k=k[1].split("&"),h=0;h<k.length;h++)if(k[h].match("course_id")){e+="&"+k[h];break}f.setAttribute("href",e);f.setAttribute("onclick","window.open(this.href); return false;");f.style.margin="0 15px 0 3px";f.className="rspkr_dr_link";f.onclick=new Function("window.open(this.href); return false;");
f.setAttribute("target","_blank");f.appendChild(g);a.className+=0<a.className.length?" "+c.drAddedClass:c.drAddedClass;g=document.createDocumentFragment();g.appendChild(f);a.parentNode.insertBefore(g,a.nextSibling)}}},Settings:c}}();
(function(l){var c=navigator.userAgent,d=/*@cc_on!@*/false,b=setTimeout;/webkit/i.test(c)?b(function(){var a=document.readyState;"loaded"==a||"complete"==a?l():b(arguments.callee,10)},10):/mozilla/i.test(c)&&!/(compati)/.test(c)||/opera/i.test(c)?document.readyState&&("loading"===document.readyState?document.addEventListener("DOMContentLoaded",l,!1):l()):d?function(){var a=document.createElement("doc:rdy");try{a.doScroll("left"),l()}catch(c){b(arguments.callee,0)}}():window.onload=l})(function(){(ReadSpeaker.DocReader.AutoAdd.Settings.docReaderOnly||
ReadSpeaker.DocReader.canInit)&&ReadSpeaker.DocReader.AutoAdd.init();ReadSpeaker.q&&ReadSpeaker.q(function(){ReadSpeaker.DocReader.AutoAdd.init()})});
